version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: bundle install
      
      - run:
          name: build the Jekyll site
          command: bundle exec jekyll build
          
      - run:
          name: Print the current time
          command: date
